ssm_app_manager:
  should_upload: true
  documents_list:
    - document_name: AWSQuickStarts-Microsoft-RdGateway-Domain-Joined
      template_name: rdgw-domain.template
    - document_name: AWSQuickStarts-Microsoft-RdGateway-Existing-VPC
      template_name: rdgw-standalone.template
    - document_name: AWSQuickStarts-Microsoft-RdGateway
      template_name: rdgw-master.template
      has_nested_stacks: true
      nested_documents:
        - resource_name: VPCStack
          document_name: AWSQuickStarts-AWS-VPC
        - resource_name: RDGWStack
          document_name: AWSQuickStarts-Microsoft-RdGateway-Existing-VPC